version: '3.4'

services:
  nginx:
    container_name: dnd-nginx
    image: nginx
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
      - ./:/code
    ports:
      - "80:80"
    depends_on:
      - php

  php:
    container_name: dnd-php
    build:
      ./.docker/php
    volumes:
      - ./:/code
    depends_on:
      - database
      - redis

  redis:
    image: redis:4-alpine

  database:
    container_name: dnd-database
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports:
      - [5432]